### ISSUE TITLE
gitignore file is missing 

### ISSUE THREAD

**Issue by nort3x** [Independent-Society-of-Knowledge/LecturePipeline#3]
repo contains binary files in `__pycache___` and `env` directory,
a `.gitignore` file should be added and binaries should be removed from git and it's history (otherwise people cloning this repo will have to download and not use them)
also this is clearly for windows and no one require those exe files and can't really contribute to this repo with it

**Comment by thisismeamir** [comment]
@AmirPAPA Make sure to add env and __pycache__ to .gitignore. Also make sure that you provide the correction via the method I explained in the video you have:
```
git fetch
git switch 3-gitignore-file-is-missing
```
add to `.gitignore`
```
git add .
git status
```
make sure there's no env or __pycache__ being tracked.
```
git commit -m"env and __pycache__ removed"
git push
```

Finally make a pull request and tag me to review.
